@url = http://admin5.test/admin/admin

### index
POST {{url}}/index

### edit

POST {{url}}/edit
Content-Type: application/json

{
  "id": 48,
  "username": "qqqqqqqq",
  "password": "aaa",
  "nickname": "aaa",
  "group": []
}


### add

POST {{url}}/add
Content-Type: application/json

{
  "username": "qqqqqqqq",
  "password": "aaa",
  "nickname": "aaa"
}

### del

POST {{url}}/del
Content-Type: application/json

{
  "id": 1
}
