### index
POST http://admin5.test/admin/admin/index

### add

POST http://admin5.test/admin/admin/add
Content-Type: application/json

{
  "username": "qqqqqqqq",
  "password": "aaa",
  "nickname": "aaa"
}

### del

POST http://admin5.test/admin/admin/del
Content-Type: application/json

{
  "id": 1
}
