@url = http://admin5.test/admin/auth_group


### index
POST  {{url}}/index

### edit
POST  {{url}}/edit

### add
POST  {{url}}/add
Content-Type: application/json

{
  "pid":7,
  "name":"ddd",
  "rules":[133,134,135,136,137,138]
}

### del
POST  {{url}}/del

### roletree
POST  {{url}}/roletree
Content-Type: application/json

{
  "id": 6
}

