### login
POST  http://admin5.test/admin/index/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

### login
POST  http://admin5.test/admin/index/login
Content-Type: application/json

{
  "username": "user1",
  "password": "user1user1"
}

### logout
POST  http://admin5.test/admin/index/logout

### userinfo
POST  http://admin5.test/admin/index/userinfo