@url = http://admin5.test/admin/rule

### index
POST  {{url}}/index

### edit
POST  {{url}}/edit

### add
POST  {{url}}/add
Content-Type: application/json

{
  "type": "menu",
  "pid": 0,
  "name": "admin/rule",
  "title": "admin/rule"
}

### del
POST  {{url}}/del
Content-Type: application/json

{
  "id": 109
}

### asyncRoutes
POST  {{url}}/asyncRoutes
Content-Type: application/json
